services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  web:
    image: riper3d/docere_proj
    entrypoint: ["/entrypoint.sh", "uwsgi", "--ini", "./config/uwsgi/uwsgi.ini"]
    restart: always

    environment:
      - DJANGO_SETTINGS_MODULE=docere.prod
      - PYTHONPATH=/code
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - uwsgi_socket:/tmp
      - static_volume:/code/docere/static
      - media_volume:/code/docere/media
      - /home/docere_user/djangoProject1/code/prod.py:/code/docere/docere/prod.py

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - uwsgi_socket:/tmp
      - ./logs/nginx:/var/log/nginx
      - static_volume:/code/docere/static
      - media_volume:/code/docere/media
    depends_on:
      - web
    restart: always

volumes:
  pgdata:
  redisdata:
  uwsgi_socket:
  static_volume:
  media_volume: